services:
  stub:
    image: mockoon/cli:latest
    volumes:
      - ./config/mockoon/api-stub.json:/data/api-stub.json:ro
    command: ["-d", "/data/api-stub.json", "-p", "3000"]
    ports:
      - "3000:3000"
    networks:
      - local-net

  lambda:
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env.local
    ports:
      - "9000:8080"
    depends_on:
      - stub
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
